[package]
name = "time-commander"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
time = "0.3.37"
